"""Brain — spinal cord: grey matter, white matter, and the intrinsic reflex circuitry.

Structures, edges and the threshold-gate forward operation for the segmental
sensorimotor core.  Each neuron is a threshold gate over equal-weight inputs: it
fires when the count of active inputs crosses a stored threshold, so the only value
held per neuron is that threshold, at log2(fan-in) bits.  No weights, no multiply,
no gradient.

Counting basis is uniform here and is not the map's usual one.  The cord is
bilateral-segmental rather than hemispheric, so counts are whole (both sides), with
the per-side value alongside where the biology records one.  That is a fourth basis
after per eye, both eyes combined, and per hemisphere.

Three things separate this module from the visual-pathway one.

First, three edge latencies are real numbers rather than None.  The lamina I
projection to the posterior thalamus carries three labelled lines whose central
conduction times are about 131, 59 and 72 ms — three delays on one anatomical edge,
the slowest 2.2x the fastest.  Everything else reads None, meaning to derive.

Second, the forward operation below cannot express most of what this tissue does.
Inhibition is what the cord computes with: reciprocal inhibition, autogenic
inhibition and recurrent inhibition are three of the six reflex arcs, the pain gate
is inhibitory at the first synapse, and the dorsal-horn interneurons divide by
transmitter into inhibitory and excitatory classes.  A count of active inputs
compared against a threshold has no term for a negative contribution.  Edges carry
their sign here so the gap is visible rather than silently dropped; adding a signed
term to the model is a change to the sizing derivation and is not this rung's.

Third, two of the loops closed inside this tissue run through muscle.  The stretch
reflex's input is muscle length and the gamma loop passes through an intrafusal
spindle fibre, and muscle is outside the scope boundary at every rung.  Those loops
can be declared and cannot be closed.

Four items this module needs are unset at every rung above and each is on the list
that must be surfaced before it is touched: the inter-structure connection topology,
the tile geometry, the sparsity, and the scheduling discipline.  Where each is
needed the module raises rather than choosing.  The learning rule is unset too, and
is the one whose absence still leaves a runnable artifact: thresholds are read-only
construction constants and nothing writes them.
"""

from __future__ import annotations

from dataclasses import dataclass
from math import ceil, log2

# --------------------------------------------------------------------------
# Element classes.
#
# Four kinds appear on or at the boundary of this section and only the first has
# a specified computation.  A pacemaker is here because the presympathetic drive
# onto the intermediolateral cell column is generated by intrinsically pacemaking
# cells rather than relayed: a threshold gate with no active inputs never fires,
# so a cell that fires from nothing is not one under any fan-in.
# --------------------------------------------------------------------------

THRESHOLD_GATE = "threshold_gate"   # spikes; stores a threshold at log2(fan-in) bits
GRADED = "graded"                   # computes without spiking; store not established
PACEMAKER = "pacemaker"             # fires without input; not a threshold gate
NONE_PRESENT = "none"               # fibre columns: no neurons, no synapse, no store

# --------------------------------------------------------------------------
# Edge sign.
#
# The threshold-gate forward operation has no term for a negative contribution.
# The sign is carried anyway, on every edge the biology types, because dropping
# it would produce a cord in which antagonist muscles co-contract, motor output
# has no gain control, and the descending analgesic gate excites the pain line.
#
# GAIN is a third value and not a sign: the descending gate carries no stimulus
# content at all, only a multiplier on another edge's transfer.  It is not an
# input to a neuron and has no place in a sum of active inputs.
# --------------------------------------------------------------------------

EXCITATORY = "+"
INHIBITORY = "-"
GAIN = "gain"                       # modulates another edge; not an input
UNTYPED = None                      # the biology does not type it here

# --------------------------------------------------------------------------
# Structures.
#
# Counts are the architecture's, carried with their basis.  `fan_in` is the
# convergence onto one neuron of this population where the biology fixes it, and
# None where it does not.  Not one fan-in in this section is fixed.
# --------------------------------------------------------------------------


@dataclass(frozen=True)
class Population:
    name: str
    kind: str
    basis: str
    count: int | None            # None where the biology has not fixed it
    fan_in: int | None           # None where the biology has not fixed it
    fan_in_bound: int = 16       # log2 cap: any fan-in under ~65,000 fits 16 bits

    @property
    def threshold_bits(self) -> int | None:
        """Stored bits per neuron under the threshold-gate model."""
        if self.kind == NONE_PRESENT:
            return 0
        if self.kind in (GRADED, PACEMAKER):
            return None          # not zero, and not log2(fan-in): not established
        if self.fan_in is None:
            return self.fan_in_bound
        if self.fan_in <= 1:
            return 0             # nothing to threshold against a single input
        return ceil(log2(self.fan_in))

    @property
    def parameter_bytes(self) -> int | None:
        bits = self.threshold_bits
        if bits is None or self.count is None:
            return None
        return self.count * bits // 8


@dataclass(frozen=True)
class Structure:
    name: str
    populations: tuple[Population, ...]
    subelements: tuple[str, ...] = ()
    adds_tissue: bool = True     # False where the entry is a circuit, not a structure

    @property
    def parameter_bytes(self) -> int | None:
        """None if any population's store is unstated — a partial sum would read as a total."""
        total = 0
        for p in self.populations:
            b = p.parameter_bytes
            if b is None:
                return None
            total += b
        return total


WHOLE = "whole (both sides)"

# The Rexed laminae are the sub-element set: an anatomical stack, dorsal to
# ventral, not a channel or isofrequency plane.  Lamina VII's three named cell
# groups are sub-elements in their own right because each projects to a different
# target: Clarke's column to cerebellum, the intermediolateral cell column to the
# sympathetic chain, the sacral parasympathetic nucleus to the pelvic viscera.
GREY_MATTER = Structure(
    "spinal cord grey matter",
    (
        # Ninety to ninety-five per cent of lamina I neurons and virtually all of
        # lamina II are interneurons, so the projection cells are a small minority
        # of a count that is stated only for the whole.
        Population("neurons", THRESHOLD_GATE, WHOLE, 200_000_000, None),
    ),
    subelements=(
        "lamina I", "lamina II", "lamina III", "lamina IV", "lamina V", "lamina VI",
        "lamina VII", "Clarke's column", "intermediolateral cell column",
        "sacral parasympathetic nucleus",
        "lamina VIII", "lamina IX", "alpha motor neurons", "gamma motor neurons",
        "lamina X",
    ),
)

# A fibre-column compartment: transmission, not processing.  No synapse occurs in
# it, so its edges are routing statements and its fan-in and fan-out are none.
# Its sub-elements are parallel channels rather than a circuit.
WHITE_MATTER = Structure(
    "spinal cord white matter",
    (Population("fibres", NONE_PRESENT, WHOLE, 0, None),),
    subelements=(
        "fasciculus gracilis", "fasciculus cuneatus",
        "anterolateral / spinothalamic system",
        "dorsal spinocerebellar tract", "ventral spinocerebellar tract",
        "lateral corticospinal tract", "anterior corticospinal tract",
        "reticulospinal tract", "vestibulospinal tract",
        "rubrospinal tract", "tectospinal tract",
        "descending modulatory fibres",
    ),
)

# A circuit, not a structure: its neurons are the grey matter's and are already
# counted there.  Its store must never be added to the section total.
REFLEX_CIRCUITS = Structure(
    "spinal reflex arcs and central pattern generators",
    (Population("neurons", NONE_PRESENT, WHOLE, 0, None),),
    subelements=(
        "stretch reflex arc", "reciprocal inhibition", "autogenic inhibition",
        "flexor withdrawal with crossed extension", "Renshaw recurrent inhibition",
        "gamma loop", "lumbar central pattern generator",
        "cervical central pattern generator",
    ),
    adds_tissue=False,
)

STRUCTURES = (GREY_MATTER, WHITE_MATTER, REFLEX_CIRCUITS)

# --------------------------------------------------------------------------
# Shape.
#
# Three of four extents are known, which is unusual in this map.  The lamina axis
# is the Rexed stack, the side axis is required by the whole-cord counting basis,
# and the segment axis is the cord's own and has no counterpart elsewhere.  The
# mediolateral axis carries the motor pools' somatotopy — medial axial, lateral
# distal limb — which the biology records qualitatively and does not pitch.
# --------------------------------------------------------------------------

LAMINAE = 10
SIDES = 2
SEGMENTS = 31                        # 8 cervical, 12 thoracic, 5 lumbar, 5 sacral, 1 coccygeal
MEDIOLATERAL = None                  # to derive: no tile pitch is measured anywhere here

SEGMENT_ORDER: tuple[str, ...] = tuple(
    [f"C{i}" for i in range(1, 9)]
    + [f"T{i}" for i in range(1, 13)]
    + [f"L{i}" for i in range(1, 6)]
    + [f"S{i}" for i in range(1, 6)]
    + ["Co1"]
)

# Three of lamina VII's cell groups exist over sub-ranges of the segment axis, so
# a dense allocation over all 31 asserts tissue where the biology says there is
# none.  Ranges are approximate in the biology and are carried as stated.
LEVEL_RESTRICTED: dict[str, tuple[str, str]] = {
    "Clarke's column": ("C8", "L2"),
    "intermediolateral cell column": ("T1", "L2"),
    "sacral parasympathetic nucleus": ("S2", "S4"),
}


def occupies(subelement: str, segment: str) -> bool:
    """Whether a sub-element exists at a segment.

    Only the three level-restricted cell groups are constrained; the laminae
    themselves run the length of the cord.  The two enlargements are a density
    fact rather than a presence fact and are not represented here, because the
    biology gives no per-segment count to represent them with.
    """
    if subelement not in LEVEL_RESTRICTED:
        return True
    lo, hi = LEVEL_RESTRICTED[subelement]
    i = SEGMENT_ORDER.index(segment)
    return SEGMENT_ORDER.index(lo) <= i <= SEGMENT_ORDER.index(hi)


# --------------------------------------------------------------------------
# Edges.
#
# An edge names its target sub-element where the biology terminates on one.  The
# primary afferent bus is sorted by modality onto different laminae, so it is two
# edges and not one, and collapsing them would delete the sorting rule.
#
# `latency_s` is real time in seconds.  It is never expressed in steps: a latency
# stated in steps has assumed a clock.
# --------------------------------------------------------------------------


@dataclass(frozen=True)
class Edge:
    source: str
    target: str
    source_sub: str | None = None
    target_sub: str | None = None
    latency_s: float | None = None      # None = to derive
    routing_only: bool = False          # a tract: no synapse, fan-in/out are none
    sign: str | None = UNTYPED
    crossed: bool = False               # laterality cannot be re-derived from either end
    carries: str = ""
    off_file: str = ""                  # far end's source file, where it leaves this one


EDGES: tuple[Edge, ...] = (
    # Inputs.  The dorsal-root ganglia lie outside the scope boundary: a peripheral
    # ganglion that carries without transducing.
    Edge("primary sensory afferents", "spinal cord grey matter", None, "lamina I",
         None, False, EXCITATORY, False,
         "nociceptive and thermoreceptive; substance P onto the neurokinin-1 receptor",
         "outside scope"),
    Edge("primary sensory afferents", "spinal cord grey matter", None, "lamina II",
         None, False, EXCITATORY, False,
         "nociceptive and thermoreceptive, before any gating", "outside scope"),
    Edge("primary sensory afferents", "spinal cord grey matter", None, "lamina IV",
         None, False, EXCITATORY, False,
         "low-threshold mechanoreceptive; laminae III-VI", "outside scope"),
    # Five descending motor tracts collapsed onto one line because their payloads
    # have not been separately typed.  Splitting them here would invent the arity.
    Edge("descending motor tracts", "spinal cord grey matter", None, "lamina IX",
         None, False, UNTYPED, False,
         "motor commands and postural drive; payload owed, five edges bundled", "5, 11, 14, 3"),
    Edge("periaqueductal gray", "spinal cord grey matter", None, "lamina II",
         None, False, GAIN, False,
         "the analgesic gate; no stimulus content, a gain on another edge", "14"),
    Edge("rostral ventromedial medulla", "spinal cord grey matter", None, "lamina II",
         None, False, GAIN, False,
         "the analgesic gate at the first synapse", "no entry anywhere"),
    Edge("raphe nuclei", "spinal cord grey matter", None, "lamina I",
         None, False, UNTYPED, False, "neuromodulatory state; payload owed", "13"),
    Edge("hypothalamus", "spinal cord grey matter", None, "intermediolateral cell column",
         None, False, UNTYPED, False, "neuromodulatory state; payload owed", "13, 14"),
    Edge("rostral ventrolateral medulla", "spinal cord grey matter", None,
         "intermediolateral cell column", None, False, EXCITATORY, False,
         "presympathetic drive; pacemaking at the source, not relayed", "14"),
    Edge("mesencephalic locomotor region", "spinal reflex arcs and central pattern generators",
         None, "lumbar central pattern generator", None, False, EXCITATORY, False,
         "start and speed command for locomotion; not the pattern itself", "14"),

    # Outputs from lamina I.  Four edges, largely one population with collaterals
    # rather than four populations: over ninety per cent of the cells projecting to
    # the periaqueductal gray also label from the parabrachial or medullary targets.
    # The three latencies are central conduction times for the three labelled lines
    # on this one edge.
    Edge("spinal cord grey matter", "posterior thalamus", "lamina I", None,
         0.131, False, EXCITATORY, True,
         "nociceptive-specific, from fusiform cells", "12"),
    Edge("spinal cord grey matter", "posterior thalamus", "lamina I", None,
         0.059, False, EXCITATORY, True,
         "thermoreceptive-specific, from pyramidal cells", "12"),
    Edge("spinal cord grey matter", "posterior thalamus", "lamina I", None,
         0.072, False, EXCITATORY, True,
         "polymodal nociceptive, from multipolar cells", "12"),
    Edge("spinal cord grey matter", "lateral parabrachial nucleus", "lamina I", None,
         None, False, EXCITATORY, True,
         "the same three lines, read for affective content; the dominant target", "14"),
    Edge("spinal cord grey matter", "caudal ventrolateral medulla", "lamina I", None,
         None, False, EXCITATORY, True, "the same payload", "14"),
    Edge("spinal cord grey matter", "periaqueductal gray", "lamina I", None,
         None, False, EXCITATORY, True, "payload owed; largely a collateral", "14"),
    Edge("spinal cord grey matter", "caudal thalamus", "lamina IV", None,
         None, False, EXCITATORY, True,
         "payload owed; neurokinin-1-receptor cells with dendrites reaching lamina I", "12"),
    Edge("spinal cord grey matter", "cerebellum", "Clarke's column", None,
         None, False, EXCITATORY, False,
         "unconscious proprioception: body configuration", "10"),
    Edge("spinal cord grey matter", "inferior olive", None, None,
         None, False, UNTYPED, False,
         "somatosensory error: the consequence against which a prediction failed", "14"),
    Edge("spinal cord grey matter", "skeletal muscle", "alpha motor neurons", None,
         None, False, EXCITATORY, False,
         "the final motor command, to extrafusal muscle", "outside scope"),
    Edge("spinal cord grey matter", "skeletal muscle", "gamma motor neurons", None,
         None, False, EXCITATORY, False,
         "to muscle-spindle intrafusal fibres", "outside scope"),
    Edge("spinal cord grey matter", "sympathetic chain ganglia",
         "intermediolateral cell column", None, None, False, EXCITATORY, False,
         "preganglionic sympathetic drive", "outside scope"),

    # White matter: routing statements.  No synapse occurs here, so fan-in and
    # fan-out are none and the payload is typed at the grey-matter end.  The
    # crossings are load-bearing and cannot be re-derived from either endpoint.
    Edge("spinal cord white matter", "gracile and cuneate nuclei", "fasciculus gracilis",
         None, None, True, None, False, "routing only; ipsilateral ascent", "5"),
    Edge("spinal cord white matter", "posterior thalamus",
         "anterolateral / spinothalamic system", None, None, True, None, True,
         "routing only; crosses at the segment of entry", "12"),
    Edge("spinal cord white matter", "ventral posterior lateral nucleus",
         "anterolateral / spinothalamic system", None, None, True, None, True,
         "routing only", "5"),
    Edge("spinal cord white matter", "cerebellum", "dorsal spinocerebellar tract",
         None, None, True, None, False, "routing only; ipsilateral, inferior peduncle", "10"),
    Edge("spinal cord white matter", "cerebellum", "ventral spinocerebellar tract",
         None, None, True, None, True,
         "routing only; crossed then re-crossing, superior peduncle", "10"),
    Edge("primary motor cortex", "spinal cord white matter", None,
         "lateral corticospinal tract", None, True, None, True,
         "routing only; crossed at the pyramidal decussation, 85-90% of fibres", "5, 11"),
    Edge("primary motor cortex", "spinal cord white matter", None,
         "anterior corticospinal tract", None, True, None, False,
         "routing only; uncrossed, axial", "5, 11"),
    Edge("reticular formation", "spinal cord white matter", None, "reticulospinal tract",
         None, True, None, False, "routing only; posture, locomotion, tone", "14"),
    Edge("vestibular nuclei", "spinal cord white matter", None, "vestibulospinal tract",
         None, True, None, False, "routing only; antigravity and balance", "3"),
    Edge("red nucleus", "spinal cord white matter", None, "rubrospinal tract",
         None, True, None, False,
         "routing only; small and largely vestigial in humans", "no entry anywhere"),
    Edge("superior colliculus", "spinal cord white matter", None, "tectospinal tract",
         None, True, None, False, "routing only; head orienting, to cervical cord", "14"),
)

# --------------------------------------------------------------------------
# Internal edges.
#
# The reflexes and the pattern generator are circuits among the grey matter's own
# neurons and add no tissue.  Their signs are the reason this section is where the
# threshold-gate model runs out: reciprocal, autogenic and recurrent inhibition are
# three of the six reflex arcs, and the pain gate is inhibitory at the first synapse.
# --------------------------------------------------------------------------


@dataclass(frozen=True)
class InternalEdge:
    source_sub: str
    target_sub: str
    sign: str | None
    latency_s: float | None
    carries: str
    leaves_scope: bool = False      # part of the path is outside the map's boundary


INTERNAL_EDGES: tuple[InternalEdge, ...] = (
    InternalEdge("primary afferent terminals", "lamina I", EXCITATORY, None,
                 "the nociceptive and thermoreceptive payload before any gating"),
    InternalEdge("lamina II inhibitory interneurons", "lamina I", INHIBITORY, None,
                 "the substrate of the pain gate; where the descending gain acts"),
    InternalEdge("lamina IV dorsal dendrites", "lamina I", None, None,
                 "dendritic reach, not a synaptic transfer; no second edge for propagation"),
    InternalEdge("dorsal horn interneurons", "lamina IX", None, None,
                 "the segmental reflex drive"),

    InternalEdge("Ia muscle-spindle afferent", "alpha motor neurons", EXCITATORY, None,
                 "stretch-reflex drive: muscle-length error corrected in one synapse",
                 leaves_scope=True),
    InternalEdge("Ia inhibitory interneuron", "alpha motor neurons", INHIBITORY, None,
                 "reciprocal inhibition, relaxing the antagonist"),
    InternalEdge("Ib Golgi-tendon afferent", "alpha motor neurons", INHIBITORY, None,
                 "autogenic inhibition via an interneuron: a tension signal limiting force",
                 leaves_scope=True),
    InternalEdge("nociceptive afferent", "alpha motor neurons", None, None,
                 "flexor withdrawal with crossed extension; opposite signs on the two limbs"),
    InternalEdge("alpha motor-neuron collateral", "alpha motor neurons", INHIBITORY, None,
                 "Renshaw recurrent inhibition: negative-feedback gain on motor output"),
    InternalEdge("gamma motor neurons", "alpha motor neurons", EXCITATORY, None,
                 "the gamma loop, via an intrafusal spindle fibre and the Ia afferent",
                 leaves_scope=True),
    InternalEdge("lumbar central pattern generator", "alpha motor neurons", None, None,
                 "the alternating locomotor pattern, generated without command or feedback"),
)

# --------------------------------------------------------------------------
# Forward operation.
#
# This is the whole of what the rungs above specify.  Equal weights reduce the dot
# product to a count, so the stored value is a threshold and the cell fires when
# the count reaches it.
# --------------------------------------------------------------------------


def threshold_gate(active_counts, thresholds):
    """Fire where the count of active inputs reaches the stored threshold.

    Integer comparison only.  No weights and no multiply, because equal weights
    reduce the dot product to a count; no gradient, because nothing here is
    differentiated.

    This covers the excitatory case and nothing else.  Callers must not route an
    inhibitory or gain edge through it: see `signed_forward`.
    """
    if len(active_counts) != len(thresholds):
        raise ValueError("one threshold per neuron")
    return [c >= t for c, t in zip(active_counts, thresholds)]


def signed_forward(*args, **kwargs):
    """The forward operation this section actually needs, and it is not specified.

    A count of active inputs compared against a threshold has no term for a
    negative contribution.  Four of the internal edges above are inhibitory and
    the biology names them by transmitter — gamma-aminobutyric acid and glycine —
    so this is not an inference about the tissue.  Reciprocal inhibition,
    autogenic inhibition and recurrent inhibition are three of the six reflex
    arcs, and the pain gate is inhibitory at the first synapse of the incoming
    line, so dropping the sign does not approximate the cord: it produces one in
    which antagonists co-contract, motor output has no gain control, and the
    descending analgesic gate excites the pain line.

    The descending gate is a third case and not a sign.  It carries no stimulus
    content, only a multiplier on another edge's transfer, so it is not an input
    to a neuron and has nowhere to go in a sum of inputs.

    Extending the model changes the stored value per neuron and therefore changes
    the parameter-memory derivation for every structure in the map, which puts it
    above this rung.
    """
    raise NotImplementedError(
        "the threshold-gate model has no signed term; four internal edges here are "
        "inhibitory and one incoming edge is a gain. Extending the model changes "
        "the sizing derivation and is not this rung's to choose."
    )


def fan_in_map(structure: Structure, subelement: str | None = None):
    """Which source lines converge on each neuron.

    Not implementable from the rungs above, and for a stronger reason than in the
    visual line.  There the topography was in the biology as prose — retinotopy,
    a space-variant compression ratio — so the function existed and only its
    authorisation was missing.  Here the pattern is not recorded at all: which Ia
    line reaches which alpha motor neuron is the somatotopy, and the biology gives
    it qualitatively (medial axial, lateral distal limb; flexor dorsal, extensor
    ventral) with no correspondence rule and no pitch.  Not one fan-in in this
    section is fixed.

    Writing this function would mean inventing the somatotopy rather than
    formalising it, and it is the inter-structure connection topology, which must
    be surfaced before it is chosen.
    """
    raise NotImplementedError(
        "connection topology is not set; it must be surfaced before it is chosen. "
        "No fan-in anywhere in this section is fixed, and the somatotopy is "
        "recorded qualitatively with no correspondence rule."
    )


def allocate(structure: Structure, subelement: str):
    """Size the threshold and activity arrays for one sub-element.

    Not implementable, and here the geometry is not what stops it.  Three of the
    four shape extents are known — 10 laminae, 2 sides, 31 segments — and only the
    mediolateral axis is open.  What blocks allocation is the partition: one count
    of ~200M covers the whole cord, and dividing it evenly across the 620
    lamina-side-segment cells asserts a uniform cord against a biology that
    describes two enlargements and three level-restricted cell groups.

    The only counted subpopulation is the lumbosacral motor pool at ~52-62k, which
    is under 0.031% of the total and constrains nothing about the rest.
    """
    if subelement not in structure.subelements:
        raise ValueError(f"{subelement!r} is not a sub-element of {structure.name}")
    raise NotImplementedError(
        f"{structure.name} carries one neuron count across "
        f"{len(structure.subelements)} sub-elements and 31 segments; no partition is "
        f"recorded, so the array for {subelement!r} cannot be sized. The array is "
        f"also ragged — see ragged_cells(). Tile geometry and sparsity are unset and "
        f"both are surface-before-touching items."
    )


def step(*args, **kwargs):
    """There is no step, and in this section the reason is visible in the output.

    Every edge has a nonzero, finite, heterogeneous latency in real time, and there
    is no global clock in the described system to replace them with.  A loop with
    real heterogeneous delays settles by its own dynamics; the same loop broken by
    registers becomes an iterated map whose trajectory depends on the update rate.

    The locomotor central pattern generator is where that stops being an argument
    about correctness and becomes a number.  It generates the alternating flexor /
    extensor and left / right pattern without descending command and without
    sensory feedback — a network manufacturing a temporal pattern out of a tonic
    input — so its period is set by the delays and time constants inside it.  Set
    every latency equal and the walking rate becomes a property of the step size.

    Unlike the visual line, this section does have latencies to schedule with:
    131, 59 and 72 ms on the lamina I thalamic edge.  The scheduling discipline is
    still not this rung's to set.
    """
    raise NotImplementedError(
        "the scheduling discipline is not set and is not this rung's to choose; "
        "the locomotor pattern generator's period would become a property of the "
        "step size rather than of the tissue."
    )


def close_gamma_loop(*args, **kwargs):
    """The gamma and stretch loops run through muscle, which no rung describes.

    The gamma loop is gamma motor neuron -> intrafusal spindle fibre -> Ia afferent
    -> alpha motor neuron, and the stretch reflex's input is muscle length.  Muscle,
    skeleton and their dynamics are outside the scope boundary by decision at every
    rung, so these loops can be declared and cannot be closed.  Whatever ends up
    driven will be servos or artificial muscle, whose dynamics are not muscle's, so
    staying biological does not dodge this — it relocates it.
    """
    raise NotImplementedError(
        "the plant is outside the scope boundary at every rung; the gamma loop and "
        "the stretch reflex cannot be closed inside the map."
    )


def learn(*args, **kwargs):
    """Nothing writes a threshold, because no learning rule is set.

    A threshold that is never written is a construction cost rather than a memory,
    which is why the module is still coherent without this: thresholds are
    read-only buffers and the cord runs open-loop.
    """
    raise NotImplementedError("no learning rule is set")


# --------------------------------------------------------------------------
# Derived checks — independent recomputation, not transcription.
# --------------------------------------------------------------------------


def sizing_report() -> str:
    lines, total, unstated, excluded = [], 0, [], []
    lines.append(f"{'structure / population':58} {'basis':18} {'neurons':>13} {'bits':>5} {'store':>12}")
    for s in STRUCTURES:
        for p in s.populations:
            bits = p.threshold_bits
            b = p.parameter_bytes
            count = f"{p.count:,}" if p.count is not None else "to derive"
            bs = "-" if bits is None else str(bits)
            if b is None:
                store = "to derive"
                unstated.append(f"{s.name} / {p.name}")
            elif not s.adds_tissue:
                store = "0 (shared)"
                excluded.append(s.name)
            else:
                store = f"{b/1e6:.1f} MB"
                total += b
            lines.append(f"{s.name + ' / ' + p.name:58} {p.basis:18} {count:>13} {bs:>5} {store:>12}")
    lines.append("")
    lines.append(f"stated total: {total/1e6:.1f} MB = {total/1e9:.3f} GB   (whole cord, both sides)")
    lines.append(f"range on the count: {197_000_000*2/1e6:.0f}-{222_000_000*2/1e6:.0f} MB "
                 f"across 197-222M neurons")
    for e in excluded:
        lines.append(f"excluded from the total, adds no tissue: {e}")
    for u in unstated:
        lines.append(f"unstated, so the total is a floor: {u}")
    return "\n".join(lines)


def realisation_gap() -> str:
    """The derived width against the width a machine integer actually takes.

    Every threshold here sits at the 16-bit log2 cap because no fan-in is fixed,
    and 16 bits is a container width, so derived and realised coincide.  The gap
    closes because nothing is derived, not because anything is known, and it
    re-opens the moment one fan-in is measured.
    """
    out = []
    for fan_in in (None, 4, 200, 5_000, 150_000):
        if fan_in is None:
            derived, label = 16, "unfixed (log2 cap)"
        else:
            derived, label = ceil(log2(fan_in)), f"fan-in {fan_in:,}"
        container = 8 if derived <= 8 else (16 if derived <= 16 else 32)
        d = 200_000_000 * derived / 8
        r = 200_000_000 * container / 8
        out.append(
            f"  {label:20} -> {derived:2} bits derived = {d/1e6:6.1f} MB, "
            f"uint{container} realised = {r/1e6:6.1f} MB, gap {100*(r-d)/d:4.1f}%"
        )
    return "\n".join(out)


def ragged_cells() -> str:
    """Which (sub-element, segment) cells the biology says do not exist.

    A dense allocation over all 31 segments asserts tissue at levels the biology
    denies, so the count is reported before any array is shaped.
    """
    out, absent = [], 0
    for sub in LEVEL_RESTRICTED:
        present = [s for s in SEGMENT_ORDER if occupies(sub, s)]
        gone = len(SEGMENT_ORDER) - len(present)
        absent += gone
        out.append(f"  {sub:34} present at {len(present):2}/{len(SEGMENT_ORDER)} segments "
                   f"({present[0]}-{present[-1]}), absent at {gone}")
    dense = LAMINAE * SIDES * len(SEGMENT_ORDER)
    out.append(f"  dense (lamina, side, segment) cells: {dense}")
    out.append(f"  cells a dense allocation would assert wrongly, per side: {absent}")
    out.append(f"  even division of 200M over {dense} cells would be "
               f"{200_000_000 // dense:,} each — an invention, not a partition")
    return "\n".join(out)


def edge_storage(update_interval_s: float, line_count: int, bits_per_value: int = 1) -> str:
    """Values in flight on the measured edges, given an update interval.

    edge_storage = line_count * ceil(latency / update_interval) * bits_per_value

    This section is the first with real latencies to put in that formula, and it is
    still not sizable, because the update interval is the scheduling discipline and
    that is unset and Micky's.  Both terms are therefore arguments with no default:
    supplying one would be choosing the discipline inside a helper.

    Storage scales with the reciprocal of the interval, so halving the interval
    doubles the memory held on every edge — which is what ties the timing decision
    to a resource rather than only to correctness.
    """
    if update_interval_s <= 0:
        raise ValueError("an update interval of zero asserts an infinite rate")
    out = []
    total = 0
    for e in EDGES:
        if e.latency_s is None:
            continue
        slots = ceil(e.latency_s / update_interval_s)
        bits = line_count * slots * bits_per_value
        total += bits
        out.append(f"  {e.carries[:34]:36} {e.latency_s*1000:5.0f} ms -> "
                   f"{slots:6,} slots, {bits/8/1e6:8.2f} MB")
    out.append(f"  total on the measured edges: {total/8/1e6:.2f} MB "
               f"at {update_interval_s*1000:g} ms and {line_count:,} lines per line class")
    return "\n".join(out)


def latency_report() -> str:
    stated = [e for e in EDGES if e.latency_s is not None]
    lines = [f"edges: {len(EDGES)}    with a stated latency: {len(stated)}    "
             f"to derive: {len(EDGES) - len(stated)}"]
    for e in stated:
        lines.append(f"  {e.source_sub or e.source} -> {e.target}: "
                     f"{e.latency_s*1000:.0f} ms  ({e.carries})")
    if stated:
        lo = min(e.latency_s for e in stated)
        hi = max(e.latency_s for e in stated)
        lines.append(f"  spread on one anatomical edge: {hi/lo:.1f}x")
    lines.append(f"internal edges: {len(INTERNAL_EDGES)}    with a stated latency: 0")
    return "\n".join(lines)


def sign_report() -> str:
    """How much of this section the unsigned forward operation can express."""
    counts: dict[str, int] = {}
    for e in INTERNAL_EDGES:
        counts[str(e.sign)] = counts.get(str(e.sign), 0) + 1
    for e in EDGES:
        if e.sign is not None and not e.routing_only:
            counts[str(e.sign)] = counts.get(str(e.sign), 0) + 1
    out = [f"  {k:6} {v}" for k, v in sorted(counts.items())]
    blocked = counts.get(INHIBITORY, 0) + counts.get(GAIN, 0)
    out.append(f"  edges the unsigned forward operation cannot express: {blocked}")
    out.append(f"  loops that leave the scope boundary: "
               f"{sum(1 for e in INTERNAL_EDGES if e.leaves_scope)}")
    return "\n".join(out)


def far_end_report() -> str:
    """Endpoints whose entry lives in another source file, and the two with none."""
    seen: dict[str, str] = {}
    for e in EDGES:
        if e.off_file:
            key = e.target if e.source.startswith("spinal") else e.source
            seen.setdefault(key, e.off_file)
    out = [f"  {k:44} {v}" for k, v in sorted(seen.items())]
    return "\n".join(out)


if __name__ == "__main__":
    print(sizing_report())
    print()
    print("threshold width, derived against realised:")
    print(realisation_gap())
    print()
    print("shape: (lamina, side, segment, mediolateral) = "
          f"({LAMINAE}, {SIDES}, {SEGMENTS}, {MEDIOLATERAL})")
    print(ragged_cells())
    print()
    print(latency_report())
    print("edge_storage() is not called here: it needs an update interval, and "
          "supplying one would set the scheduling discipline.")
    print()
    print("edge sign, and what the model cannot express:")
    print(sign_report())
    print()
    print("far ends, recorded and not opened:")
    print(far_end_report())
    print()
    for fn, label in ((fan_in_map, "connectivity"), (signed_forward, "signed forward"),
                      (step, "scheduler"), (close_gamma_loop, "plant"), (learn, "learning")):
        try:
            fn(GREY_MATTER) if fn is fan_in_map else fn()
        except NotImplementedError as exc:
            print(f"{label:16} blocked: {exc}")
    try:
        allocate(GREY_MATTER, "intermediolateral cell column")
    except NotImplementedError as exc:
        print(f"{'allocation':16} blocked: {exc}")
